### ISSUE TITLE
Add option to use HTTPS

### ISSUE THREAD

**Issue by rugk** [mrkschan/isgd-creator#2]
[Is.gd supports HTTPS](https://is.gd/) (through Cloudflare) so it would be nice if this creator could optionally support creating HTTPS links too.

You just have to add an `s`. :smiley:

**Comment by mrkschan** [comment]
I'm sorry that https was not used. It should be the default transport.

**Comment by rugk** [comment]
https://github.com/mrkschan/isgd-creator/commit/c87946da911046c2aeda5740a1f479e7839a074a - Nice, but also the (short-URL) URL which is returned should be using HTTPS. (e.g. https://is.gd/kOlREh instead of http://is.gd/kOlREh)

**Comment by mrkschan** [comment]
@rugk fyi, submitted a new release, it's pending review now.

**Comment by rugk** [comment]
Nice :+1:
